name: Build
on:
  push:
    tags:
      - '*'
  pull_request:
permissions:
  pull-requests: write
  contents: write
jobs:
  build-image:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build --no-cache -t quay.io/krkn-chaos/krkn-service-hijacking:latest .
          docker tag quay.io/krkn-chaos/krkn-service-hijacking:latest quay.io/krkn-chaos/krkn-service-hijacking:${GITHUB_REF##*/}
      - name: Login in quay
        run: docker login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
        env:
          QUAY_USER: ${{ secrets.QUAY_USERNAME }}
          QUAY_TOKEN: ${{ secrets.QUAY_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push quay.io/krkn-chaos/krkn-syn-flood:latest
          docker push quay.io/krkn-chaos/krkn-syn-flood:${GITHUB_REF##*/}